wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    code_path: code/atari/ppo_rle.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.20
    start_time: 1731050522
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      4: 3.8.20
      5: 0.12.21
      8:
      - 5
anneal_lr:
  desc: null
  value: false
batch_size:
  desc: null
  value: 16384
capture_video:
  desc: null
  value: false
capture_video_interval:
  desc: null
  value: 10
clip_coef:
  desc: null
  value: 0.1
clip_vloss:
  desc: null
  value: true
cuda:
  desc: null
  value: true
ent_coef:
  desc: null
  value: 0.01
env_id:
  desc: null
  value: Alien-v5
eval_interval:
  desc: null
  value: 0
exp_name:
  desc: null
  value: ppo_rle
ext_coef:
  desc: null
  value: 1.0
feature_size:
  desc: null
  value: 16
gae_lambda:
  desc: null
  value: 0.95
gamma:
  desc: null
  value: 0.999
gpu_id:
  desc: null
  value: 0
int_coef:
  desc: null
  value: 0.01
int_gamma:
  desc: null
  value: 0.99
int_vf_coef:
  desc: null
  value: 0.5
learning_rate:
  desc: null
  value: 0.0003
local_dir:
  desc: null
  value: ./results
max_grad_norm:
  desc: null
  value: 0.5
minibatch_size:
  desc: null
  value: 4096
norm_adv:
  desc: null
  value: true
norm_rle_features:
  desc: null
  value: true
normalize_ext_rewards:
  desc: null
  value: true
num_envs:
  desc: null
  value: 128
num_eval_envs:
  desc: null
  value: 32
num_eval_episodes:
  desc: null
  value: 32
num_iterations_feat_norm_init:
  desc: null
  value: 1
num_minibatches:
  desc: null
  value: 4
num_steps:
  desc: null
  value: 128
save_rle:
  desc: null
  value: false
seed:
  desc: null
  value: 1
sticky_action:
  desc: null
  value: true
switch_steps:
  desc: null
  value: 500
target_kl:
  desc: null
  value: null
tau:
  desc: null
  value: 0.005
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 40000000
track:
  desc: null
  value: true
update_epochs:
  desc: null
  value: 4
use_local_dir:
  desc: null
  value: false
vf_coef:
  desc: null
  value: 0.5
wandb_entity:
  desc: null
  value: null
wandb_project_name:
  desc: null
  value: random-latent-exploration
z_layer_init:
  desc: null
  value: ortho_1.41:0.0
